service: fetch-file-and-store-in-s3

frameworkVersion: ">=1.1.0"

custom:
  bucket: <your-bucket-name>

provider:
  name: aws
  runtime: nodejs8.10
  stage: dev
  region: us-west-1
  iamRoleStatements:
    - Effect: Allow
      Action:
        - s3:PutObject
        - s3:PutObjectAcl
      Resource: "arn:aws:s3:::${self:custom.bucket}/*"
  vpc: # Optional VPC. But if you use VPC then both subproperties (securityGroupIds and subnetIds) are required
    securityGroupIds:
      - securityGroupId1
      - securityGroupId2
    subnetIds:
      - subnetId1
functions:
  save:
    handler: handler.save
    environment:
      BUCKET: ${self:custom.bucket}
